# Site settings
title: 경영학과 최우영의 블로그
url: "http://wychoi911.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Seoul
description: >
  description

# Your information
email: wychoi911@gmail.com
author: 최우영
# avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
avatar: "//github.com/wychoi911/wychoi911.github.io/blob/master/media/lil-face-4-512.png"
profile: <br> 경영학과의 자존심을 지키자
#twitter_username: twitter_username
github_username:  wychoi911

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: maengdev   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-sitemap

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
